# Site
name: "GO-EUC"
title: "GO-EUC"
description: "The research platform for the EUC space"
meta_description: "The research platform for the EUC space"
logo: 'assets/images/logo-white.png'
favicon: 'assets/images/favicon.ico'
paginate: 10
baseurl: ''
email: 'info@logitblog.com'
slack: 'https://join.slack.com/t/go-euc/shared_invite/enQtNTQxNTUxMTk5MzE5LTA0NzIzMDUzYmZjMTFiMTc4YmQ4M2Y1MGRjYzkyNjk2ZjkzOGVhNDliZjVkZjM5MzlkNjVlNjVlZTYwYTVmNWE'
google_analytics: 'UA-125461461-1'
disqus: 'ict-r'
permalink: /:title/

# Authors
authors:
  ryan:
    name: Ryan
    display_name: Ryan Ververs-Bijkerk
    company: RawWorks
    title: 'Technical Evangelist'
    picture: 'assets/images/authors/ryan.png'
    web: https://www.logitblog.com
    twitter: https://twitter.com/logitblog
    linkedin: https://www.linkedin.com/in/ryanbijkerk
    github: https://github.com/RyanBijkerk
    reddit: https://www.reddit.com/u/ryanbijkerk
    page: ryan-ververs-bijkerk
    description: "Ryan is currently a Technical Evangelist at RawWorks focused on the EUC and Code area. Ryan is primarily focusing on the user experience in centralized desktop environments. "
  eltjo:
    name: Eltjo
    display_name: Eltjo van Gulik
    company: RawWorks
    title: 'Principal Consultant'
    picture: 'assets/images/authors/eltjo.png'
    web: https://www.netwerkhelden.nl/cms/
    twitter: https://twitter.com/eltjovg
    linkedin: https://www.linkedin.com/in/eltjovangulik/
    page: eltjo-van-gulik
    description: "Eltjo van Gulik is a Workspace Consultant and enthusiast. Citrix aficionado. Wannabee PowerShell buff. Blogger. Father and husband. Social, a tad pedantic and suitably lazy. Citrix CTP, PTEC member and SME."
  omar:
    name: Omar
    display_name: Omar Bouhaj
    company: 'SLTN Inter Access'
    title: 'Solutions Architect EUC'
    picture: 'assets/images/authors/omar.png'
    twitter: https://twitter.com/omar_bouhaj
    linkedin: https://www.linkedin.com/in/omarbouhaj/
    page: omar-bouhaj
    description: "Dedicated, passionate and innovative IT professional. Omar is an enthusiastic and driven technical consultant and currently a consultant at ICT-Partners West, focused on the End-User Computing (EUC) area. With the primary focus on the user experience in centralized desktop environments."
  sven:
    name: Sven
    display_name: Sven Huisman
    company: Nutanix
    title: Solutions Architect
    picture: 'assets/images/authors/sven.png'
    web: https://svenhuisman.com/
    twitter: https://twitter.com/svenh
    linkedin: https://www.linkedin.com/in/svenhuisman/
    page: sven-huisman
    description: "Sven is working as a solutions architect at Nutanix with the focus on End User Computing. The opinions expressed here represent his own and not those of his employer."
  krishan:
    name: Krishan
    display_name: Krishan Khoesial
    company: Cegeka
    title: Workspace Consultant
    picture: 'assets/images/authors/krishan.png'
    linkedin: https://www.linkedin.com/in/kvkhoesial/
    page: krishan-khoesial
    description: "Krishan is a Workspace Consultant at Cegeka. He has more than a decade experience in End User Computing and conducted many performance scans for customers, national and international."
  marcel:
    name: Marcel
    display_name: Marcel Beck
    company: ICT-Partners
    title: Workspace Consultant
    picture: 'assets/images/authors/marcel.png'
    linkedin: https://www.linkedin.com/in/msbeck/
    page: marcel-beck
    description: "Marcel is a full-time Workspace Consultant/Architect and part-time beer drinker from the north of The Netherlands."
  ruud:
    name: Ruud
    display_name: Ruud Hund
    company: Cegeka
    title: Thought Leader Connected Workspace
    picture: 'assets/images/authors/ruud.png'
    twitter: https://twitter.com/RuudHund
    linkedin: https://www.linkedin.com/in/ruudhund/
    page: ruud-hund
    description: "Ruud is a Thought Leader Connected Workspace at Cegeka. Ruud has over 10+ years experience in designing and building network infrastructures."
  bas:
    name: Bas
    display_name: Bas Stapelbroek
    company: Citrix
    title: Sales Engineer
    picture: 'assets/images/authors/bas.png'
    web: http://www.basstapelbroek.com/
    twitter: https://twitter.com/hapster84
    linkedin: https://www.linkedin.com/in/basstapelbroek/
    page: bas-stapelbroek
    description: "Bas Stapelbroek is a sales engineer and works for Citrix in the Netherlands."
  tom:
    name: Tom 
    display_name: Tom de Jong
    company: RawWorks
    title: Workspace Consultant
    picture: 'assets/images/authors/tom.png'
    linkedin: https://www.linkedin.com/in/tom-de-jong-5131809a/
    page: tom-de-jong
    description: "Tom de Jong is working as a EUC consultant on the Citrix portfolio. He is based in the most beautiful part from the Netherlands, which is the West-Friesland region."
  patrick:
    name: Patrick 
    display_name: Patrick van den Born
    company: van den Born IT Consultancy
    title: Senior IT Consultant | IT Architect
    picture: 'assets/images/authors/patrick.png'
    web: https://patrickvandenborn.blogspot.com/
    twitter: https://twitter.com/pvdnborn
    linkedin: https://www.linkedin.com/in/patrick-van-den-born-2b3567a/
    page: patrick-van-den-born
    description: "Patrick van den Born is an independent senior consultant and IT architect focussed on Citrix End User Computing, NVIDIA GRID Technology and cloud computing."
  gerjon:
    name: Gerjon 
    display_name: Gerjon Kunst
    company: RawWorks
    title: Principal consultant
    picture: 'assets/images/authors/gerjon.png'
    web: https://www.gerjon.com
    twitter: https://twitter.com/gkunst
    linkedin: https://www.linkedin.com/in/gerjonkunst/
    page: gerjon-kunst
    description: "Gerjon Kunst is Principal Consultant at RawWorks in het Netherlands, focusing on future Workspace and Cloud."
  jeff:
    name: Jeff 
    display_name: Jeff Stokes
    company: Tanium
    title: Principal Engineer
    picture: 'assets/images/authors/jeff.png'
    web: https://illuminati.services/
    twitter: https://twitter.com/WindowsPerf
    linkedin: https://www.linkedin.com/in/jeffstokes/
    page: jeff-stokes
    description: "Jeff Stokes is a Principal Engineer at Tanium, and an expert in the fields of Windows performance analytics, debugging, VDI, and Windows imaging and deployment."
  benny:
    name: Benny 
    display_name: Benny Tritsch
    company: Dr. Tritsch IT Consulting
    title: Owner 
    picture: 'assets/images/authors/benny.png'
    web: http://drtritsch.com/
    twitter: https://twitter.com/drtritsch
    linkedin: https://www.linkedin.com/in/drtritsch
    page: benny-tritsch
    description: "Dr. Benny Tritsch is a self-employed end-user computing expert located in Germany, specializing in modern workplace designs, graphics remoting and end-user experience analysis."

# Sponsors
sponsors:
  tricerat:
    name: Tricerat
    level: 2
    date: 2022-07-31
    logo-light: 'assets/images/sponsor/tricerat/logo-white.png'
    logo: 'assets/images/sponsor/tricerat/logo.png'
    page: 'tricerat'
    site: 'https://www.tricerat.com'
  loadgen:
    name: LoadGen
    level: 2
    date: 2022-06-31
    logo-light: 'assets/images/sponsor/loadgen/logo-white.png'
    logo: 'assets/images/sponsor/loadgen/logo.png'
    page: 'loadgen'
    site: 'https://www.loadgen.com'
  ict-p:
    name: ICT-Partners
    level: 2
    date: 2020-08-31
    logo-light: 'assets/images/sponsor/ict-partners/logo.png'
    logo: 'assets/images/sponsor/ict-partners/logo.png'
    page: 'ict-partners'
    site: 'https://www.ict-partners.nl'

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# Other
markdown: kramdown
highlighter: rouge
